
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import { AuthProvider } from "@/context/authcontext/authcontext";
import MyHeader from "./components/layout/Headers";
import "@fontsource/vazirmatn"
import { CartProvider } from "@/context/cartContext/CartContext";
import FooterSaeed from "./components/layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body >
       
       <Toaster position="bottom-center" />
         <AuthProvider>
          <CartProvider>
            <MyHeader />
            <main>{children}</main>
            <FooterSaeed/>
          </CartProvider>
        </AuthProvider>
       
      </body>
    </html>
  );
}
